#!/usr/bin/env php
<?php

use OpenShareFile\Core;
use OpenShareFile\Task\Clean;
use Symfony\Component\Console\Application;

// OpenShareFile autoload
require_once __DIR__.DIRECTORY_SEPARATOR.'Core'.DIRECTORY_SEPARATOR.'Autoload.php';
Core\Autoload::register();

// vendor autoload
require_once __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'autoload.php';

// configuration
require_once __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'config'.DIRECTORY_SEPARATOR.'config.php';

$application = new Application();
$application->add(new Clean);
$application->run();